"""Initial migration with corrected Category model

Revision ID: 44748cbe7306
Revises: 
Create Date: 2025-06-17 20:38:02.919704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44748cbe7306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('unicode_emoji', sa.String(length=10), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('unicode_emoji')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
